name: "[Expérimental – .yml] Manque d'attribution"
description: Attribution inexistante, incomplète, difficile à trouver, nécessite une interaction particulière...
title: "Titre du signalement"
labels: [bug, enhancement]
body:
- type: input
  id: concerne
  attributes:
    label: Ce signalement concerne...
    description: Pour signaler un site Web, une application, un magazine, une pancarte...
    placeholder: "https://exemple.fr/carte.html..."
- type: dropdown
  id: presence
  attributes:
    label: Présence de l'attribution
    description: L'attribution est-elle présente ?
    options:
      - ❌ Pas d'attribution
      - ⚠️ Attribution partielle
      - ✔️ Avec attribution
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      - ❌ **Pas d'attribution**
      - ⚠️ **Attribution partielle** *« © OSM »...*
      - ✔️ **Avec attribution** *« © les contributeurs d’OpenStreetMap »...*
- type: checkboxes
  id: verifications
  attributes:
    label: Vérifications
    options:
      - label: Il y a un lien vers [openstreetmap.org/copyright](https://www.openstreetmap.org/copyright)
      - label: Une interaction est nécessaire pour afficher l'attribution
- type: markdown
  attributes:
    value: |
      - Interaction : L'utilisateur doit agir pour voir l'attribution. (Survoler/cliquer sur un bouton ℹ️, un lien...)
- type: dropdown
  id: tuiles
  attributes:
    label: (Facultatif) Quel est le fournisseur de tuiles ?
    multiple: true
    options:
      - openstreetmap.org
      - openstreetmap.fr
      - CyclOSM
      - Humanitaire
      - OpenRiverboatMap
      - Autre/inconnu
- type: checkboxes
  id: contact
  attributes:
    label: Le responsable a-t-il été contacté ?
    options:
      - label: Le responsable a été contacté
- type: textarea
  id: contact-info
  attributes:
    label: Informations concernant la prise de contact
    description: Quand, comment (Twitter, email...), quelle était (brièvement) la réponse...
    value: |
      - Contacté le :
      - Par (email, Twitter...) :
- type: textarea
  id: commentaire
  attributes:
    label: Commentaire
    description: Toute autre information...
